export const METER_SIZE = 150;
export const GRID_METERS = 2.5;

export const DEFAULT_PERSON_HEIGHT_METERS = 1.67;
export const DEFAULT_PERSON_HEIGHT = DEFAULT_PERSON_HEIGHT_METERS * METER_SIZE; // remove?
